### ISSUE TITLE
[Question] imports on terrain and steps

### ISSUE THREAD

**Issue by z4r4tu5tr4** [radish-bdd/radish#192] opened 2017-11-08 18:02 UTC
Hello everybody, i'm trying run the documentation quickstart's example and have a question related at import files. When I try execute radish importing files in the project, like:

```Python
# terrain file
from mymodule import function
```
aways get the same error:

`ModuleNotFoundError: No module named 'mymodule'`

In a google search I find a [same problem in stackoverflow](https://stackoverflow.com/questions/45418083/import-module-fails-from-the-python-radish-bdd-executable?newreg=ed1dc7ae5af94fa1bee796242b74de21). But the answer suggest run radish using   `radish -b radish features/myfeature.feature`. But for me it dosen't works.

A try change paths using `-b`, but without success. I create a [gist](https://gist.github.com/z4r4tu5tr4/8f7b001b5ba3612d5ace891a1e25f8ee) with my simple code example and a has this path structure:

```
.
├── calc
│   ├── calculator.py
│   └── __init__.py
├── features
│   └── SumNumbers.feature
└── radish
    ├── __init__.py
    ├── steps.py
    └── terrain.py
```

And to execute: `radish -b radish features/SumNumbers.feature`

sorry my english and thanks for your time.

**Comment by timofurrer** [comment] 2017-11-08 20:22
The problem is most likely that your `calc` Python package is not part of the Python import path (`PYTHONPATH`, `sys.path`, ...).

Try this: `PYTHONPATH=. radish -b radish features/SumNumbers.feature`

**Comment by timofurrer** [comment] 2017-11-09 18:55
I'm going to close this for now. If it didn't work, just let me know and I'll re-open it. :tada:

**Closed by timofurrer** 2017-11-09 18:55 UTC
Labels: question

**Comment by z4r4tu5tr4** [comment] 2017-11-16 15:04
I prefer use in code, but has a problems with PEP8, like a E402. But it is not a huge problem.

thanks for your time @timofurrer .

if anywone has the same problem:

```Python
from sys import path
path.append('./calc_example/calc')
import calculator
```

**Comment by z4r4tu5tr4** [comment] 2017-11-16 15:05
@timofurrer, what do you think if we create a repository with project examples?
